# This configuration is for local development of supabase edge functions
# For more information: https://supabase.com/docs/guides/functions/local-development

[functions]
[functions.game-operations]
verify_jwt = false
import_map = "./import_map.json"

[functions.matchmaking]
verify_jwt = false
import_map = "./import_map.json"

[auth]
enable_anonymous_sign_ins = true

[auth.external.turnstile]
enabled = true
site_key = "env(NEXT_PUBLIC_TURNSTILE_SITE_KEY)"
secret = "env(TURNSTILE_SECRET_KEY)"

# Realtime configuration
[realtime]
enabled = true

# Studio configuration
[studio]
port = 3010