version: '3.8'

services:
  # PostgreSQL Database (optional - can use external Supabase instead)
  postgres:
    image: supabase/postgres:15.1.0.117
    container_name: next-chess-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d/migrations
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_DB: ${POSTGRES_DB:-next_chess}
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      POSTGRES_HOST_AUTH_METHOD: md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-next_chess}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - coolify
    labels:
      - coolify.managed=true
      - coolify.type=database
      - coolify.name=next-chess-db

  # Next.js Chess Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # These should point to your external Supabase instance
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      cache_from:
        - node:20-alpine
    image: next-chess:latest
    container_name: next-chess-app
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      HOSTNAME: "0.0.0.0"
      # REQUIRED: Set these in your Coolify environment variables
      # Get these from your Supabase project settings at https://app.supabase.com
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      # Direct database connection to local PostgreSQL
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/${POSTGRES_DB:-next_chess}
      SKIP_ENV_VALIDATION: ${SKIP_ENV_VALIDATION:-true}
      # Disable Next.js telemetry
      NEXT_TELEMETRY_DISABLED: 1
      # Memory optimization for sharp on Linux
      NODE_OPTIONS: "--max-old-space-size=2048"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # Resource limits for better container management
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coolify
    labels:
      # Coolify will auto-generate most labels, we just need basics
      - coolify.managed=true
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`chess.rndev.site`)
      - traefik.http.services.app.loadbalancer.server.port=3000

volumes:
  postgres_data:
    driver: local

networks:
  coolify:
    external: true